include $(ROOT)/make/comdef.mak

FILES = decagonal_dipyramid.wrl
FILES+= dihexagonal_dipyramid.wrl
FILES+= dioctagonal_dipyramid.wrl
FILES+= elongated_square_dipyramid.wrl
FILES+= elongated_triangular_dipyramid.wrl
FILES+= enneagonal_dipyramid.wrl
FILES+= heptagonal_dipyramid.wrl
FILES+= hexagonal_dipyramid.wrl
FILES+= octagonal_dipyramid2.wrl
FILES+= octagonal_dipyramid.wrl
FILES+= pentagonal_dipyramid.wrl
FILES+= triangular_dipyramid.wrl

INSTALLDIR =$(DATADIR)/data/vrml
include $(MAKEDIR)/files.mak

SUBDIRS+= cgm

include $(MAKEDIR)/subdirs.mak
