include $(ROOT)/make/comdef.mak

FILES = elongated_pentagonal_pyramid.wrl
FILES+= elongated_square_pyramid.wrl
FILES+= elongated_triangular_pyramid.wrl
FILES+= gyroelongated_pentagonal_pyramid.wrl
FILES+= gyroelongated_square_pyramid.wrl
FILES+= hexagonal_pyramid.wrl
FILES+= octagonal_pyramid.wrl
FILES+= square_pyramid.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak

SUBDIRS = cgm

include $(MAKEDIR)/subdirs.mak
