include $(ROOT)/make/comdef.mak

FILES = Agent.hpp
FILES+= Event.hpp
FILES+= Event_handler.hpp
FILES+= Keyboard_event.hpp
FILES+= Motion_event.hpp
FILES+= Passive_motion_event.hpp
FILES+= Mouse_event.hpp
FILES+= Redraw_event.hpp
FILES+= Reset_event.hpp
FILES+= Reshape_event.hpp
FILES+= Simulate_event.hpp
FILES+= Start_event.hpp
FILES+= Stop_event.hpp
FILES+= Tick_event.hpp
FILES+= Draw_event.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
