include $(ROOT)/make/comdef.mak

FILES = cgm_tetrahedron.wrl
FILES+= cgm_cube.wrl
FILES+= cgm_octahedron.wrl
FILES+= cgm_icosahedron.wrl
FILES+= cgm_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
