include $(ROOT)/make/comdef.mak

FILES = cuboctahedron.wrl
FILES+= deltoidal_hexecontahedron.wrl
FILES+= disdyakistriacontahedron.wrl
FILES+= icosidodecahedron.wrl
FILES+= pentagonal_hexecontahedron.wrl
FILES+= pentakisdodecahedron.wrl
FILES+= rhombic_triacontahedron.wrl
FILES+= rhombicosidodecahedron.wrl
FILES+= snub_dodecahedron.wrl
FILES+= triakisicosahedron.wrl
FILES+= truncated_cube.wrl
FILES+= truncated_cuboctahedron.wrl
FILES+= truncated_dodecahedron.wrl
FILES+= truncated_icosahedron.wrl
FILES+= truncated_icosidodecahedron.wrl
FILES+= truncated_octahedron.wrl
FILES+= truncated_tetrahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak

SUBDIRS = cgm
SUBDIRS+= ngm
SUBDIRS+= platonic

include $(MAKEDIR)/subdirs.mak
