// Copyright (c) 2004 Israel.
// All rights reserved.
//
// This file is part of SGAL; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; version 2.1 of the
// License. See the file LICENSE.LGPL distributed with SGAL.
//
// Licensees holding a valid commercial license may use this file in
// accordance with the commercial license agreement provided with the
// software.
//
// This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING
// THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Author(s)     : Efi Fogel         <efifogel@gmail.com>

#ifndef SGAL_GEOMETRY_HPP
#define SGAL_GEOMETRY_HPP

/*! \file
 * A base class for all geometries.
 *
 * A geometry is a base (abstract) class. Currently it only
 * contains a unique id which is used as a display list id.
 *
 * Inherits from Container
 */

#include "SGAL/basic.hpp"
#include "SGAL/Container.hpp"
#include "SGAL/Types.hpp"
#include "SGAL/Vector4f.hpp"
#include "SGAL/Matrix4f.hpp"
#include "SGAL/Math_defs.hpp"
#include "SGAL/Sphere_bound.hpp"

SGAL_BEGIN_NAMESPACE

class Draw_action;
class Isect_action;
class Container_proto;
class Element;
class Field_info;

class SGAL_SGAL_DECL Geometry : public Container {
public:
  enum {
    FIRST = Container::LAST - 1,
    SPHERE_BOUND,
    BOUND_MODE,
    GENERATE_COLOR,
    GENERATE_TEX_COORD,
    LAST
  };

  enum Bound_mode {
    STATIC,
    DYNAMIC
  };

  /*! Constructor */
  Geometry(Boolean proto = false);

  /*! Destructor */
  virtual ~Geometry() {}

  /*! Initialize the node prototype. */
  virtual void init_prototype();

  /*! Delete the node prototype. */
  virtual void delete_prototype();

  /*! Obtain the node prototype. */
  virtual Container_proto* get_prototype();

  /// \name field handlers
  //@{
  Sphere_bound* sphere_bound_handle(const Field_info*)
  { return &m_sphere_bound; }
  Boolean* generate_color_handle(const Field_info*)
  { return &m_generate_color; }
  Boolean* generate_tex_coord_handle(const Field_info*)
  { return &m_generate_tex_coord; }
  //@}

  /*! Set the attributes of this node. */
  virtual void set_attributes(Element* elem);

  // virtual Attribute_list get_attributes();

  //void set_box_bound(const Box_bound & box_bound);
  //void get_box_bound(Box_bound & box_bound);

  /*! Draw the geometry. */
  virtual void draw(Draw_action* action) = 0;

  /*! Draw the geometry in selection mode. */
  virtual void isect(Isect_action* action) = 0;

  /*! Calculare the sphere bound of the geometry. */
  virtual Boolean clean_sphere_bound() = 0;

  virtual const Sphere_bound* get_sphere_bound(bool& changed);

  const Sphere_bound* get_sphere_bound() {
    bool dummy;
    return get_sphere_bound(dummy);
  }

  /*! Set the flag that indicates that the sphere bound should be cleaned. */
  virtual void sphere_bound_changed(const Field_info* field_info = nullptr);

  /*! Return true if the current matrix contains scaling.
   * \todo has_scale() doesn't belong to Geometry!
   */
  virtual Boolean has_scale();

  /*! Determine whether the geometry has texture coordinates.
   */
  virtual Boolean has_tex_coord();

  /*! Determine whether the geometry has color.
   * If the geometry has color, by default light is kept disabled, and the
   * color is used (instead of the normal and the material).
   * \return true if the geometry has color and false otherwise.
   */
  virtual Boolean has_color();

  /*! Determine whether color should be generated.
   * Most geometries cannot generate color; thus, this is rarely used.
   */
  Boolean do_generate_color();

  /*! Set the flag that indicates whether color should be generated.
   */
  void set_generate_color(Boolean flag);

  /*! Determine whether texture coordinates should be generated. */
  Boolean do_generate_tex_coord();

  /*! Set the flag that indicates whether texture coordinates should be
   * generated.
   */
  void set_generate_tex_coord(Boolean flag);

protected:
  /*! The sphere bound of the node. */
  Sphere_bound m_sphere_bound;

  /*! Indicatres whether the bounding sphere is valid. */
  Boolean m_dirty_sphere_bound;

  /*! Indicates whether the bounding box is pewviously set. */
  Boolean m_bb_is_pre_set;

  /*! Indicates whether color should be generated by the geometry. */
  Boolean m_generate_color;

  /*! Indicates whether texture coordinates should be generated by the
   * geometry (as oppsed to the texture generation capabilities of the
   * graphics system, for example).
   */
  Boolean m_generate_tex_coord;

private:
  /*! The prototype of this node. */
  static Container_proto* s_prototype;

  // Default values
  static const Boolean s_def_generate_color;
  static const Boolean s_def_generate_tex_coord;
};

//! \brief determines whether the geometry has color.
inline Boolean Geometry::has_color() { return false; }

//! \brief determines whether the geometry has texture coordinate.
inline Boolean Geometry::has_tex_coord() { return false; }

//! \brief determines whether color should be generated.
inline Boolean Geometry::do_generate_color()
{ return m_generate_tex_coord; }

//! \brief sets the flag that indicates whether color should be generated.
inline void Geometry::set_generate_color(Boolean flag)
{ m_generate_color = flag; }

//! \brief determines whether texture coordinates should be generated.
inline Boolean Geometry::do_generate_tex_coord()
{ return m_generate_tex_coord; }

/*! \brief sets the flag that indicates whether texture coordinates should be
 * generated.
 */
inline void Geometry::set_generate_tex_coord(Boolean flag)
{ m_generate_tex_coord = flag; }

SGAL_END_NAMESPACE

#endif
