include $(ROOT)/make/comdef.mak

FILES = Boundary_set.hpp
FILES+= calculate_multiple_normals_per_vertex.hpp
FILES+= Color_array.hpp
FILES+= Coord_array.hpp
FILES+= Coord_array_2d.hpp
FILES+= Coord_array_3d.hpp
FILES+= Coord_minkowski.hpp
FILES+= Coord_transformer.hpp
FILES+= Extrusion.hpp
FILES+= Geometry.hpp
FILES+= Geo_set.hpp
FILES+= Indexed_face_set.hpp
FILES+= Indexed_line_set.hpp
FILES+= Indexed_face_set_mask.hpp
FILES+= Mesh_set.hpp
FILES+= Normal_array.hpp
FILES+= Piece.hpp
FILES+= Polyhedron.hpp
FILES+= Polyhedron_geo_builder.hpp
FILES+= Tex_coord_array.hpp
FILES+= Tex_coord_array_2d.hpp
FILES+= Tex_coord_array_3d.hpp
FILES+= Tex_coord_array_4d.hpp
FILES+= Text.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
