// Copyright (c) 2018 Israel.
// All rights reserved.
//
// This file is part of SGAL; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; version 2.1 of the
// License. See the file LICENSE.LGPL distributed with SGAL.
//
// Licensees holding a valid commercial license may use this file in
// accordance with the commercial license agreement provided with the
// software.
//
// This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING
// THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Author(s): Efi Fogel         <efifogel@gmail.com>

#ifndef DXF_BLOCK_HPP
#define DXF_BLOCK_HPP

#include <string>
#include <vector>
#include <map>

#include <boost/shared_ptr.hpp>

#include "SGAL/basic.hpp"
#include "SGAL/Types.hpp"

#include "dxf/basic.hpp"

SGAL_BEGIN_NAMESPACE

class Group;

SGAL_END_NAMESPACE

DXF_BEGIN_NAMESPACE

class Dxf_base_entity;

struct SGAL_SGAL_DECL Dxf_block {

  typedef boost::shared_ptr<SGAL::Group>                Shared_group;

  /// Member records
  //@{

  SGAL::String m_handle; // Handle
  SGAL::String m_owner_handle; // Soft-pointer ID/handle to owner object
  int16_t m_paper_space; // Absent or zero indicates entity is in model space.
                        // 1 indicates entity is in paper space (optional).
  SGAL::String m_layer_name; // Layer name
  SGAL::String m_name;  // Block name
  int16_t m_flags;      // Block-type flags (bit-coded values, may be combined):
                        // 0 = Indicates none of the following flags apply
                        // 1 = This is an anonymous block generated by hatching,
                        //     associative dimensioning, other internal
                        //     operations, or an application
                        // 2 = This block has non-constant attribute definitions
                        //     (this bit is not set if the block has any
                        //     attribute definitions that are constant, or has
                        //     no attribute definitions at all)
                        // 4 = This block is an external reference (xref)
                        // 8 = This block is an xref overlay
                        // 16 = This block is externally dependent
                        // 32 = This is a resolved external reference, or
                        //      dependent of an external reference (ignored on
                        //      input)
                        // 64 = This definition is a referenced external
                        //     reference (ignored on input)
  double m_base_point[3]; // Base point
  SGAL::String m_xref_path_name; // Xref path name
  SGAL::String m_description; // Block description (optional)
  std::map<SGAL::String, std::vector<SGAL::String> > m_xdata; // Begin xdata
                        // "{", "}" (opt.)

  //@}

  /*! Construct
   */
  Dxf_block() : m_paper_space(0) {}

  /*! Destruct.
   */
  ~Dxf_block();

  //! The entities
  std::vector<Dxf_base_entity*> m_entities;

  //! The Group sub-graph represenetd by the block.
  Shared_group m_group;
};

DXF_END_NAMESPACE

#endif
