include $(ROOT)/make/comdef.mak
SUBDIRS = engines
SUBDIRS+= events
SUBDIRS+= geo
SUBDIRS+= geometries
SUBDIRS+= interpolators
SUBDIRS+= IO
SUBDIRS+= lights
SUBDIRS+= loaders
SUBDIRS+= primitives
SUBDIRS+= sensors
SUBDIRS+= utilities
SUBDIRS+= SGAL
include $(MAKEDIR)/subdirs.mak
