include $(ROOT)/make/comdef.mak

FILES = sgm_dioctagonal_pyramid.wrl
FILES+= sgm_hexagonal_pyramid.wrl
FILES+= sgm_octagonal_pyramid.wrl
FILES+= sgm_squahsed_dioctagonal_pyramid.wrl
FILES+= sgm_square_pyramid.wrl
FILES+= sgm_square_pyramid2.wrl
FILES+= sgm_squashed_octagonal_pyramid.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
