include $(ROOT)/make/comdef.mak

FILES = cgm_dioctagonal_pyramid.wrl
FILES+= cgm_hexagonal_pyramid.wrl
FILES+= cgm_octagonal_pyramid.wrl
FILES+= cgm_squahsed_dioctagonal_pyramid.wrl
FILES+= cgm_square_pyramid.wrl
FILES+= cgm_square_pyramid2.wrl
FILES+= cgm_squashed_octagonal_pyramid.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
