include $(ROOT)/make/comdef.mak

FILES = nef_tetrahedron.wrl
FILES+= nef_cube.wrl
FILES+= nef_octahedron.wrl
FILES+= nef_icosahedron.wrl
FILES+= nef_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
