include $(ROOT)/make/comdef.mak

FILES = ngm_geodesic_sphere1.wrl
FILES+= ngm_geodesic_sphere2.wrl
FILES+= ngm_geodesic_sphere3.wrl
FILES+= ngm_geodesic_sphere4.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
