include $(ROOT)/make/comdef.mak

FILES = sgm_mink_dioct_pyr_ort_dioct_pyr.wrl
FILES+= sgm_mink_exact_icos_icos.wrl
FILES+= sgm_mink_geo4_rot_geo4.wrl
FILES+= sgm_mink_icos_icos.wrl
FILES+= sgm_mink_pent_hex_trun_icosido.wrl
FILES+= sgm_mink_rat_dioct_pyr_ort_dioct_pyr.wrl
FILES+= sgm_mink_rat_ellip_ort_ellip.wrl
FILES+= sgm_mink_rat_geo4_rot_geo4.wrl
FILES+= sgm_mink_rat_icos_icos.wrl
FILES+= sgm_mink_rat_pent_hex_trun_icosido.wrl
FILES+= sgm_mink_rat_sqs_sqr_pyr_ort_sqs_sqr_pyr.wrl
FILES+= sgm_mink_rat_tet_cube.wrl
FILES+= sgm_mink_rat_tet_tet.wrl
FILES+= sgm_mink_sqs_sqr_pyr_ort_sqs_sqr_pyr.wrl
FILES+= sgm_mink_tet_cube.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
