# Copyright (c) 2004  Israel.
# All rights reserved.
#
# This file is part of the collection of Efi Fogel.
# You may redistribute it under the terms of the Q Public License version 1.0.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# $Source$
# $Revision: 6623 $
# $Name$
#
# Author(s)     : Efi Fogel

include $(ROOT)/make/comdef.mak

FILES  = Exact_number_type.hpp
FILES += Exact_kernel.hpp
FILES += Exact_polyhedron.hpp
FILES += Approximate_kernel.hpp
FILES += Min_sphere.hpp

INSTALLDIR =$(INCDIR)/SCGAL
include $(MAKEDIR)/files.mak
