include $(ROOT)/make/comdef.mak

FILES = ellip.wrl
FILES+= ellip_1.0_0.5_0.5_16.wrl
FILES+= ellip_16.wrl
FILES+= ellips_16.wrl
FILES+= ellipsh_1.wrl
FILES+= ellipsh_10.wrl
FILES+= ellipsh_11.wrl
FILES+= ellipsh_12.wrl
FILES+= ellipsh_16.wrl
FILES+= ellipsh_2.wrl
FILES+= ellipsh_32.wrl
FILES+= ellipsh_4.wrl
FILES+= ellipsh_8.wrl
FILES+= ellipsh_9.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak

SUBDIRS+= cgm

include $(MAKEDIR)/subdirs.mak
