include $(ROOT)/make/comdef.mak

FILES = adaptable_factory.hpp
FILES+= common.hpp
FILES+= convenience.hpp
FILES+= extension.hpp
FILES+= factory.hpp
FILES+= factory_map.hpp
FILES+= filesystem.hpp
FILES+= parameter.hpp
FILES+= parameter_map.hpp
FILES+= registry.hpp
FILES+= shared_library.hpp
FILES+= type_map.hpp

INSTALLDIR =$(INCDIR)/boost/extension
SUBDIRS = impl

include $(MAKEDIR)/files.mak
include $(MAKEDIR)/subdirs.mak
