include $(ROOT)/make/comdef.mak

FILES = sgm_geodesic_sphere1.wrl
FILES+= sgm_geodesic_sphere2.wrl
FILES+= sgm_geodesic_sphere3.wrl
FILES+= sgm_geodesic_sphere4.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
