include $(ROOT)/make/comdef.mak

FILES = ngm_mink_geo4_geo4.wrl
FILES+= ngm_mink_pent_hex_trun_icosido.wrl
FILES+= ngm_mink_rat_geo4_rot_geo4.wrl
FILES+= ngm_mink_tet_cube.wrl
FILES+= ngm_mink_dioct_pyr_ort_dioct_pyr.wrl

INSTALLDIR =$(DATADIR)/data/vrml
include $(MAKEDIR)/files.mak
