include $(ROOT)/make/comdef.mak

FILES = Arc.hpp
FILES+= Box.hpp
FILES+= Cone.hpp
FILES+= Cylinder.hpp
FILES+= Cylindrical_patch.hpp
FILES+= Sphere.hpp
FILES+= Ellipsoid.hpp
FILES+= Torus.hpp
FILES+= Geodesic.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
