include $(ROOT)/make/comdef.mak

FILES = cgm_geodesic_sphere1.wrl
FILES+= cgm_geodesic_sphere2.wrl
FILES+= cgm_geodesic_sphere3.wrl
FILES+= cgm_geodesic_sphere4.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
