include $(ROOT)/make/comdef.mak

FILES = ch_tetrahedron.wrl
FILES+= ch_cube.wrl
FILES+= ch_octahedron.wrl
FILES+= ch_icosahedron.wrl
FILES+= ch_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
