include $(ROOT)/make/comdef.mak

FILES = tri_tetrahedron.wrl
FILES+= tri_cube.wrl
FILES+= tri_octahedron.wrl
FILES+= tri_icosahedron.wrl
FILES+= tri_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
