include $(ROOT)/make/comdef.mak

FILES = Bit_mask.hpp
FILES+= Item_primitive.hpp
FILES+= Math_defs.hpp
FILES+= Array_types.hpp
FILES+= Types.hpp
FILES+= Version_info.hpp
FILES+= Inexact_kernel.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
