include $(ROOT)/make/comdef.mak

FILES = geodesic_sphere1.wrl
FILES+= geodesic_sphere2.wrl
FILES+= geodesic_sphere3.wrl
FILES+= geodesic_sphere4.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak

SUBDIRS+= cgm ngm

include $(MAKEDIR)/subdirs.mak
