include $(ROOT)/make/comdef.mak
FILES = split_star_decomposed-5.wrl
FILES+= split_star_decomposed-8.wrl
FILES+= split_star_decomposed.wrl
FILES+= split_star.wrl
INSTALLDIR =$(ROOT)/data
include $(MAKEDIR)/files.mak
