include $(ROOT)/make/comdef.mak

FILES = sgm_dihexagonal_dipyramid.wrl
FILES+= sgm_dioctagonal_dipyramid.wrl
FILES+= sgm_octagonal_dipyramid.wrl
FILES+= sgm_squashed_dioctagonal_pyramid.wrl

INSTALLDIR =$(DATADIR)/data/vrml
include $(MAKEDIR)/files.mak
