// Copyright (c) 2018 Israel.
// All rights reserved.
//
// This file is part of SGAL; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; version 2.1 of the
// License. See the file LICENSE.LGPL distributed with SGAL.
//
// Licensees holding a valid commercial license may use this file in
// accordance with the commercial license agreement provided with the
// software.
//
// This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING
// THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Author(s): Efi Fogel         <efifogel@gmail.com>

#include <map>

#include "SGAL/basic.hpp"
#include "SGAL/Types.hpp"

#include "dxf/basic.hpp"
#include "dxf/Dxf_header_full_wrapper.hpp"

DXF_BEGIN_NAMESPACE

/*! This file contains the description of DXF header variables. In
 * particular, it consists of the initialization of a mapping from variable
 * names to structs that contains information about the the variables. The
 * domain struct consists of the handle to the member in the header struct and
 * a list of codes that precede the values of the variable, respectively.
 * The DXF header members listed below are extracted from
 *   http://help.autodesk.com/view/ACD/2017/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A
 * The page is entitled "Autodesk Autocad 2017", which may lead the belief that
 * the list is complete. However, some variables had to be added.
 * Additional variables where taken from
 *  https://docs.rs/dxf/0.2.0/dxf/struct.Header.html
 *
 * Also, some of the codes listed in the Autodesk page where erroneous (i.e.,
 * HIDETEXT, INTERSECTIONDISPLAY).
 */

const std::map<SGAL::String, Dxf_header_full_wrapper::Header_member>
Dxf_header_full_wrapper::s_header_members = {
  {"ACADMAINTVER",    {&Dxf_header_full::m_acadmaintver, {70}}},
  {"ACADVER",         {&Dxf_header_full::m_acadver, {1}}},
  {"ANGBASE",         {&Dxf_header_full::m_angbase, {50}}},
  {"ANGDIR",          {&Dxf_header_full::m_angdir, {70}}},
  {"ATTMODE",         {&Dxf_header_full::m_attmode, {70}}},
  {"AUNITS",          {&Dxf_header_full::m_aunits, {70}}},
  {"AUPREC",          {&Dxf_header_full::m_auprec, {70}}},
  {"CECOLOR",         {&Dxf_header_full::m_cecolor, {62}}},
  {"CELTSCALE",       {&Dxf_header_full::m_celtscale, {40}}},
  {"CELTYPE",         {&Dxf_header_full::m_celtype, {6}}},
  {"CELWEIGHT",       {&Dxf_header_full::m_celweight, {370}}},
  {"CEPSNID",         {&Dxf_header_full::m_cepsnid, {390}}},
  {"CEPSNTYPE",       {&Dxf_header_full::m_cepsntype, {380}}},
  {"CHAMFERA",        {&Dxf_header_full::m_chamfera, {40}}},
  {"CHAMFERB",        {&Dxf_header_full::m_chamferb, {40}}},
  {"CHAMFERC",        {&Dxf_header_full::m_chamferc, {40}}},
  {"CHAMFERD",        {&Dxf_header_full::m_chamferd, {40}}},
  {"CLAYER",          {&Dxf_header_full::m_clayer, {8}}},
  {"CMLJUST",         {&Dxf_header_full::m_cmljust, {70}}},
  {"CMLSCALE",        {&Dxf_header_full::m_cmlscale, {40}}},
  {"CMLSTYLE",        {&Dxf_header_full::m_cmlstyle, {2}}},
  {"CSHADOW",         {&Dxf_header_full::m_cshadow, {280}}},
  {"DIMADEC",         {&Dxf_header_full::m_dimadec, {70}}},
  {"CUSTOMPROPERTY",  {&Dxf_header_full::m_customproperty, {1}}},
  {"CUSTOMPROPERTYTAG",{&Dxf_header_full::m_custompropertytag, {1}}},
  {"DIMALT",          {&Dxf_header_full::m_dimalt, {70}}},
  {"DIMALTD",         {&Dxf_header_full::m_dimaltd, {70}}},
  {"DIMALTF",         {&Dxf_header_full::m_dimaltf, {40}}},
  {"DIMALTRND",       {&Dxf_header_full::m_dimaltrnd, {40}}},
  {"DIMALTTD",        {&Dxf_header_full::m_dimalttd, {70}}},
  {"DIMALTTZ",        {&Dxf_header_full::m_dimalttz, {70}}},
  {"DIMALTU",         {&Dxf_header_full::m_dimaltu, {70}}},
  {"DIMALTZ",         {&Dxf_header_full::m_dimaltz, {70}}},
  {"DIMAPOST",        {&Dxf_header_full::m_dimapost, {1}}},
  {"DIMASO",          {&Dxf_header_full::m_dimaso, {70}}}, // Obsolete; see DIMASSOC.
  {"DIMASSOC",        {&Dxf_header_full::m_dimassoc, {280}}},
  {"DIMASZ",          {&Dxf_header_full::m_dimasz, {40}}},
  {"DIMATFIT",        {&Dxf_header_full::m_dimatfit, {70}}},
  {"DIMAUNIT",        {&Dxf_header_full::m_dimaunit, {70}}},
  {"DIMAZIN",         {&Dxf_header_full::m_dimazin, {70}}},
  {"DIMBLK",          {&Dxf_header_full::m_dimblk, {1}}},
  {"DIMBLK1",         {&Dxf_header_full::m_dimblk1, {1}}},
  {"DIMBLK2",         {&Dxf_header_full::m_dimblk2, {1}}},
  {"DIMCEN",          {&Dxf_header_full::m_dimcen, {40}}},
  {"DIMCLRD",         {&Dxf_header_full::m_dimclrd, {70}}},
  {"DIMCLRE",         {&Dxf_header_full::m_dimclre, {70}}},
  {"DIMCLRT",         {&Dxf_header_full::m_dimclrt, {70}}},
  {"DIMDEC",          {&Dxf_header_full::m_dimdec, {70}}},
  {"DIMDLE",          {&Dxf_header_full::m_dimdle, {40}}},
  {"DIMDLI",          {&Dxf_header_full::m_dimdli, {40}}},
  {"DIMDSEP",         {&Dxf_header_full::m_dimdsep, {70}}},
  {"DIMEXE",          {&Dxf_header_full::m_dimexe, {40}}},
  {"DIMEXO",          {&Dxf_header_full::m_dimexo, {40}}},
  {"DIMFAC",          {&Dxf_header_full::m_dimfac, {40}}},
  {"DIMFRAC",         {&Dxf_header_full::m_dimfrac, {70}}},
  {"DIMGAP",          {&Dxf_header_full::m_dimgap, {40}}},
  {"DIMJUST",         {&Dxf_header_full::m_dimjust, {70}}},
  {"DIMLDRBLK",       {&Dxf_header_full::m_dimldrblk, {1}}},
  {"DIMLFAC",         {&Dxf_header_full::m_dimlfac, {40}}},
  {"DIMLIM",          {&Dxf_header_full::m_dimlim, {70}}},
  {"DIMLUNIT",        {&Dxf_header_full::m_dimlunit, {70}}},
  {"DIMLWD",          {&Dxf_header_full::m_dimlwd, {70}}},
  {"DIMLWE",          {&Dxf_header_full::m_dimlwe, {70}}},
  {"DIMPOST",         {&Dxf_header_full::m_dimpost, {1}}},
  {"DIMRND",          {&Dxf_header_full::m_dimrnd, {40}}},
  {"DIMSAH",          {&Dxf_header_full::m_dimsah, {70}}},
  {"DIMSCALE",        {&Dxf_header_full::m_dimscale, {40}}},
  {"DIMSD1",          {&Dxf_header_full::m_dimsd1, {70}}},
  {"DIMSD2",          {&Dxf_header_full::m_dimsd2, {70}}},
  {"DIMSE1",          {&Dxf_header_full::m_dimse1, {70}}},
  {"DIMSE2",          {&Dxf_header_full::m_dimse2, {70}}},
  {"DIMSHO",          {&Dxf_header_full::m_dimsho, {70}}},
  {"DIMSOXD",         {&Dxf_header_full::m_dimsoxd, {70}}},
  {"DIMSTYLE",        {&Dxf_header_full::m_dimstyle, {2}}},
  {"DIMTAD",          {&Dxf_header_full::m_dimtad, {70}}},
  {"DIMTDEC",         {&Dxf_header_full::m_dimtdec, {70}}},
  {"DIMTFAC",         {&Dxf_header_full::m_dimtfac, {40}}},
  {"DIMTIH",          {&Dxf_header_full::m_dimtih, {70}}},
  {"DIMTIX",          {&Dxf_header_full::m_dimtix, {70}}},
  {"DIMTM",           {&Dxf_header_full::m_dimtm, {40}}},
  {"DIMTMOVE",        {&Dxf_header_full::m_dimtmove, {70}}},
  {"DIMTOFL",         {&Dxf_header_full::m_dimtofl, {70}}},
  {"DIMTOH",          {&Dxf_header_full::m_dimtoh, {70}}},
  {"DIMTOL",          {&Dxf_header_full::m_dimtol, {70}}},
  {"DIMTOLJ",         {&Dxf_header_full::m_dimtolj, {70}}},
  {"DIMTP",           {&Dxf_header_full::m_dimtp, {40}}},
  {"DIMTSZ",          {&Dxf_header_full::m_dimtsz, {40}}},
  {"DIMTVP",          {&Dxf_header_full::m_dimtvp, {40}}},
  {"DIMTXSTY",        {&Dxf_header_full::m_dimtxsty, {7}}},
  {"DIMTXT",          {&Dxf_header_full::m_dimtxt, {40}}},
  {"DIMTZIN",         {&Dxf_header_full::m_dimtzin, {70}}},
  {"DIMUPT",          {&Dxf_header_full::m_dimupt, {70}}},
  {"DIMZIN",          {&Dxf_header_full::m_dimzin, {70}}},
  {"DISPSILH",        {&Dxf_header_full::m_dispsilh, {70}}},
  {"DRAGVS",          {&Dxf_header_full::m_dragvs, {349}}},
  {"DWGCODEPAGE",     {&Dxf_header_full::m_dwgcodepage, {3}}},
  {"ELEVATION",       {&Dxf_header_full::m_elevation, {40}}},
  {"ENDCAPS",         {&Dxf_header_full::m_endcaps, {280}}},
  {"EXTMAX",          {&Dxf_header_full::m_extmax, {10, 20, 30}}},
  {"EXTMIN",          {&Dxf_header_full::m_extmin, {10, 20, 30}}},
  {"EXTNAMES",        {&Dxf_header_full::m_extnames, {290}}},
  {"FILLETRAD",       {&Dxf_header_full::m_filletrad, {40}}},
  {"FILLMODE",        {&Dxf_header_full::m_fillmode, {70}}},
  {"FINGERPRINTGUID", {&Dxf_header_full::m_fingerprintguid, {2}}},
  {"HALOGAP",         {&Dxf_header_full::m_halogap, {280}}},
  {"HANDSEED",        {&Dxf_header_full::m_handseed, {5}}},
  {"HIDETEXT",        {&Dxf_header_full::m_hidetext, {280}}},
  {"HYPERLINKBASE",   {&Dxf_header_full::m_hyperlinkbase, {1}}},
  {"INDEXCTL",        {&Dxf_header_full::m_indexctl, {280}}},
  {"INSBASE",         {&Dxf_header_full::m_insbase, {10, 20, 30}}},
  {"INSUNITS",        {&Dxf_header_full::m_insunits, {70}}},
  {"INTERFERECOLOR",  {&Dxf_header_full::m_interferecolor, {62}}},
  {"INTERFEREOBJVS",  {&Dxf_header_full::m_interfereobjvs, {345}}},
  {"INTERFEREVPVS",   {&Dxf_header_full::m_interferevpvs, {346}}},
  {"INTERSECTIONCOLOR", {&Dxf_header_full::m_intersectioncolor, {70}}},
  {"INTERSECTIONDISPLAY", {&Dxf_header_full::m_intersectiondisplay, {280}}},
  {"JOINSTYLE",       {&Dxf_header_full::m_joinstyle, {280}}},
  {"LASTSAVEDBY",     {&Dxf_header_full::m_last_saved_by, {1}}},
  {"LIMCHECK",        {&Dxf_header_full::m_limcheck, {70}}},
  {"LIMMAX",          {&Dxf_header_full::m_limmax, {10, 20}}},
  {"LIMMIN",          {&Dxf_header_full::m_limmin, {10, 20}}},
  {"LTSCALE",         {&Dxf_header_full::m_ltscale, {40}}},
  {"LUNITS",          {&Dxf_header_full::m_lunits, {70}}},
  {"LUPREC",          {&Dxf_header_full::m_luprec, {70}}},
  {"LWDISPLAY",       {&Dxf_header_full::m_lwdisplay, {290}}},
  {"MAXACTVP",        {&Dxf_header_full::m_maxactvp, {70}}},
  {"MEASUREMENT",     {&Dxf_header_full::m_measurement, {70}}},
  {"MENU",            {&Dxf_header_full::m_menu, {1}}},
  {"MIRRTEXT",        {&Dxf_header_full::m_mirrtext, {70}}},
  {"OBSCOLOR",        {&Dxf_header_full::m_obscolor, {70}}},
  {"OBSLTYPE",        {&Dxf_header_full::m_obsltype, {280}}},
  {"OLESTARTUP",      {&Dxf_header_full::m_olestartup, {290}}},
  {"ORTHOMODE",       {&Dxf_header_full::m_orthomode, {70}}},
  {"PDMODE",          {&Dxf_header_full::m_pdmode, {70}}},
  {"PDSIZE",          {&Dxf_header_full::m_pdsize, {40}}},
  {"PELEVATION",      {&Dxf_header_full::m_pelevation, {40}}},
  {"PEXTMAX",         {&Dxf_header_full::m_pextmax, {10, 20, 30}}},
  {"PEXTMIN",         {&Dxf_header_full::m_pextmin, {10, 20, 30}}},
  {"PINSBASE",        {&Dxf_header_full::m_pinsbase, {10, 20, 30}}},
  {"PLIMCHECK",       {&Dxf_header_full::m_plimcheck, {70}}},
  {"PLIMMAX",         {&Dxf_header_full::m_plimmax, {10, 20}}},
  {"PLIMMIN",         {&Dxf_header_full::m_plimmin, {10, 20}}},
  {"PLINEGEN",        {&Dxf_header_full::m_plinegen, {70}}},
  {"PLINEWID",        {&Dxf_header_full::m_plinewid, {40}}},
  {"PROJECTNAME",     {&Dxf_header_full::m_projectname, {1}}},
  {"PROXYGRAPHICS",   {&Dxf_header_full::m_proxygraphics, {70}}},
  {"PSLTSCALE",       {&Dxf_header_full::m_psltscale, {70}}},
  {"PSTYLEMODE",      {&Dxf_header_full::m_pstylemode, {290}}},
  {"PSVPSCALE",       {&Dxf_header_full::m_psvpscale, {40}}},
  {"PUCSBASE",        {&Dxf_header_full::m_pucsbase, {2}}},
  {"PUCSNAME",        {&Dxf_header_full::m_pucsname, {2}}},
  {"PUCSORG",         {&Dxf_header_full::m_pucsorg, {10, 20, 30}}},
  {"PUCSORGBACK",     {&Dxf_header_full::m_pucsorgback, {10, 20, 30}}},
  {"PUCSORGBOTTOM",   {&Dxf_header_full::m_pucsorgbottom, {10, 20, 30}}},
  {"PUCSORGFRONT",    {&Dxf_header_full::m_pucsorgfront, {10, 20, 30}}},
  {"PUCSORGLEFT",     {&Dxf_header_full::m_pucsorgleft, {10, 20, 30}}},
  {"PUCSORGRIGHT",    {&Dxf_header_full::m_pucsorgright, {10, 20, 30}}},
  {"PUCSORGTOP",      {&Dxf_header_full::m_pucsorgtop, {10, 20, 30}}},
  {"PUCSORTHOREF",    {&Dxf_header_full::m_pucsorthoref, {2}}},
  {"PUCSORTHOVIEW",   {&Dxf_header_full::m_pucsorthoview, {70}}},
  {"PUCSXDIR",        {&Dxf_header_full::m_pucsxdir, {10, 20, 30}}},
  {"PUCSYDIR",        {&Dxf_header_full::m_pucsydir, {10, 20, 30}}},
  {"QTEXTMODE",       {&Dxf_header_full::m_qtextmode, {70}}},
  {"REGENMODE",       {&Dxf_header_full::m_regenmode, {70}}},
  {"SHADEDGE",        {&Dxf_header_full::m_shadedge, {70}}},
  {"SHADEDIF",        {&Dxf_header_full::m_shadedif, {70}}},
  {"SHADOWPLANELOCATION", {&Dxf_header_full::m_shadowplanelocation, {40}}},
  {"SKETCHINC",       {&Dxf_header_full::m_sketchinc, {40}}},
  {"SKPOLY",          {&Dxf_header_full::m_skpoly, {70}}},
  {"SORTENTS",        {&Dxf_header_full::m_sortents, {280}}},
  {"SPLFRAME",        {&Dxf_header_full::m_splframe, {70}}},
  {"SPLINESEGS",      {&Dxf_header_full::m_splinesegs, {70}}},
  {"SPLINETYPE",      {&Dxf_header_full::m_splinetype, {70}}},
  {"STYLESHEET",      {&Dxf_header_full::m_stylesheet, {1}}},
  {"SURFTAB1",        {&Dxf_header_full::m_surftab1, {70}}},
  {"SURFTAB2",        {&Dxf_header_full::m_surftab2, {70}}},
  {"SURFTYPE",        {&Dxf_header_full::m_surftype, {70}}},
  {"SURFU",           {&Dxf_header_full::m_surfu, {70}}},
  {"SURFV",           {&Dxf_header_full::m_surfv, {70}}},
  {"TDCREATE",        {&Dxf_header_full::m_tdcreate, {40}}},
  {"TDINDWG",         {&Dxf_header_full::m_tdindwg, {40}}},
  {"TDUCREATE",       {&Dxf_header_full::m_tducreate, {40}}},
  {"TDUPDATE",        {&Dxf_header_full::m_tdupdate, {40}}},
  {"TDUSRTIMER",      {&Dxf_header_full::m_tdusrtimer, {40}}},
  {"TDUUPDATE",       {&Dxf_header_full::m_tduupdate, {40}}},
  {"TEXTSIZE",        {&Dxf_header_full::m_textsize, {40}}},
  {"TEXTSTYLE",       {&Dxf_header_full::m_textstyle, {7}}},
  {"THICKNESS",       {&Dxf_header_full::m_thickness, {40}}},
  {"TILEMODE",        {&Dxf_header_full::m_tilemode, {70}}},
  {"TRACEWID",        {&Dxf_header_full::m_tracewid, {40}}},
  {"TREEDEPTH",       {&Dxf_header_full::m_treedepth, {70}}},
  {"UCSBASE",         {&Dxf_header_full::m_ucsbase, {2}}},
  {"UCSNAME",         {&Dxf_header_full::m_ucsname, {2}}},
  {"UCSORG",          {&Dxf_header_full::m_ucsorg, {10, 20, 30}}},
  {"UCSORGBACK",      {&Dxf_header_full::m_ucsorgback, {10, 20, 30}}},
  {"UCSORGBOTTOM",    {&Dxf_header_full::m_ucsorgbottom, {10, 20, 30}}},
  {"UCSORGFRONT",     {&Dxf_header_full::m_ucsorgfront, {10, 20, 30}}},
  {"UCSORGLEFT",      {&Dxf_header_full::m_ucsorgleft, {10, 20, 30}}},
  {"UCSORGRIGHT",     {&Dxf_header_full::m_ucsorgright, {10, 20, 30}}},
  {"UCSORGTOP",       {&Dxf_header_full::m_ucsorgtop, {10, 20, 30}}},
  {"UCSORTHOREF",     {&Dxf_header_full::m_ucsorthoref, {2}}},
  {"UCSORTHOVIEW",    {&Dxf_header_full::m_ucsorthoview, {70}}},
  {"UCSXDIR",         {&Dxf_header_full::m_ucsxdir, {10, 20, 30}}},
  {"UCSYDIR",         {&Dxf_header_full::m_ucsydir, {10, 20, 30}}},
  {"UNITMODE",        {&Dxf_header_full::m_unitmode, {70}}},
  {"USERI1",          {&Dxf_header_full::m_useri1, {70}}},
  {"USERI2",          {&Dxf_header_full::m_useri2, {70}}},
  {"USERI3",          {&Dxf_header_full::m_useri3, {70}}},
  {"USERI4",          {&Dxf_header_full::m_useri4, {70}}},
  {"USERI5",          {&Dxf_header_full::m_useri5, {70}}},
  {"USERR1",          {&Dxf_header_full::m_userr1, {40}}},
  {"USERR2",          {&Dxf_header_full::m_userr2, {40}}},
  {"USERR3",          {&Dxf_header_full::m_userr3, {40}}},
  {"USERR4",          {&Dxf_header_full::m_userr4, {40}}},
  {"USERR5",          {&Dxf_header_full::m_userr5, {40}}},
  {"USRTIMER",        {&Dxf_header_full::m_usrtimer, {70}}},
  {"VERSIONGUID",     {&Dxf_header_full::m_versionguid, {2}}},
  {"VISRETAIN",       {&Dxf_header_full::m_visretain, {70}}},
  {"WORLDVIEW",       {&Dxf_header_full::m_worldview, {70}}},
  {"XCLIPFRAME",      {&Dxf_header_full::m_xclipframe, {290}}},
  {"XEDIT",           {&Dxf_header_full::m_xedit, {290}}}
};

DXF_END_NAMESPACE
