include $(ROOT)/make/comdef.mak

FILES = Drag_sensor.hpp
FILES+= Flow_sensor.hpp
FILES+= Key_sensor.hpp
FILES+= Navigation_sensor.hpp
FILES+= Proximity_sensor.hpp
FILES+= Single_key_sensor.hpp
FILES+= Time_sensor.hpp
FILES+= Touch_sensor.hpp
FILES+= View_sensor.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
