include $(ROOT)/make/comdef.mak

FILES = sgm_tetrahedron.wrl
FILES+= sgm_cube.wrl
FILES+= sgm_octahedron.wrl
FILES+= sgm_icosahedron.wrl
FILES+= sgm_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
