include $(ROOT)/make/comdef.mak

FILES = adaptable_factory_free_functions.hpp
FILES+= adaptable_factory.hpp
FILES+= adaptable_factory_set.hpp
FILES+= create_func.hpp
FILES+= create.hpp
FILES+= decl.hpp
FILES+= factory.hpp
FILES+= factory_map.hpp
FILES+= function.hpp
FILES+= library_impl.hpp
FILES+= shared_library.hpp
FILES+= typeinfo.hpp

INSTALLDIR =$(INCDIR)/boost/extension/impl
include $(MAKEDIR)/files.mak
