include $(ROOT)/make/comdef.mak

FILES = cgm_dihexagonal_dipyramid.wrl
FILES+= cgm_dioctagonal_dipyramid.wrl
FILES+= cgm_octagonal_dipyramid.wrl
FILES+= cgm_squashed_dioctagonal_pyramid.wrl

INSTALLDIR =$(DATADIR)/data/vrml
include $(MAKEDIR)/files.mak
