# Copyright (c) 2004  Israel.
# All rights reserved.
#
# This file is part of the collection of Efi Fogel.
# You may redistribute it under the terms of the Q Public License version 1.0.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# $Source$
# $Revision: 6414 $
#
# Author(s)     : Efi Fogel

include $(ROOT)/make/comdef.mak

FILES = Degenerate_plane_3.hpp

INSTALLDIR =$(INCDIR)/SCGAL
include $(MAKEDIR)/files.mak
