include $(ROOT)/make/comdef.mak

FILES = pol_tetrahedron.wrl
FILES+= pol_cube.wrl
FILES+= pol_octahedron.wrl
FILES+= pol_icosahedron.wrl
FILES+= pol_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/vrml
include $(MAKEDIR)/files.mak
