ifdef BASELIBS

TEMPLIBS = $(BASELIBS:<=$(LIBLINKPREFIX))
LLDLIBS += $(TEMPLIBS:>=$(LIBLINKSUFFIX))

ifndef LIBS

TEMPLIBS2 = $(BASELIBS:<=$(LIBDIR)/$(LIBFILEPREFIX))
LIBS = $(TEMPLIBS2:>=$(LIBFILESUFFIX))

else
ifdef BASELIBS_AND_LIBS

TEMPLIBS2 = $(BASELIBS:<=$(LIBDIR)/$(LIBFILEPREFIX))
LIBS += $(TEMPLIBS2:>=$(LIBFILESUFFIX))

endif
endif
endif
