include $(ROOT)/make/comdef.mak
FILES = Writer.hpp
FILES+= Formatter.hpp
FILES+= Vrml_formatter.hpp
# FILES = io.hpp
# FILES+= Color.hpp
# FILES+= io_tags.hpp
INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
