# Copyright (c) 2012  Israel.
# All rights reserved.
#
# This file is part of the collection of Efi Fogel.
# You may redistribute it under the terms of the Q Public License version 1.0.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# Author(s)     : Efi Fogel

include $(ROOT)/make/comdef.mak

FILES = Ego_geo.hpp
FILES += Ego_voxelizer.hpp

INSTALLDIR =$(INCDIR)/SEGO
include $(MAKEDIR)/files.mak
