include $(ROOT)/make/comdef.mak

FILES = Bounding_box.hpp
FILES+= Line.hpp
FILES+= Matrix3f.hpp
FILES+= Matrix4f.hpp
FILES+= Plane.hpp
FILES+= Rotation.hpp
FILES+= Vector2f.hpp
FILES+= Vector2u.hpp
FILES+= Vector2sh.hpp
FILES+= Vector3f.hpp
FILES+= Vector3sh.hpp
FILES+= Vector4f.hpp
FILES+= Vector4ub.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
