include $(ROOT)/make/comdef.mak

FILES = Color_interpolator.hpp
FILES+= Comp_color_interpolator.hpp
FILES+= Comp_normal_interpolator.hpp
FILES+= Comp_position_interpolator.hpp
FILES+= Comp_rotation_interpolator.hpp
FILES+= Comp_scalar_interpolator.hpp
FILES+= Comp_vector3f_interpolator.hpp
FILES+= Interpolator.hpp
FILES+= Normal_interpolator.hpp
FILES+= Position_interpolator.hpp
FILES+= Rotation_interpolator.hpp
FILES+= Scalar_interpolator.hpp
FILES+= Vector3f_interpolator.hpp
FILES+= Coordinate_interpolator.hpp

INSTALLDIR =$(INCDIR)/SGAL
include $(MAKEDIR)/files.mak
