include $(ROOT)/make/comdef.mak

FILES = ngm_tetrahedron.wrl
FILES+= ngm_cube.wrl
FILES+= ngm_octahedron.wrl
FILES+= ngm_icosahedron.wrl
FILES+= ngm_dodecahedron.wrl

INSTALLDIR =$(DATADIR)/data/vrml
include $(MAKEDIR)/files.mak
